# Generated by Django 4.2.2 on 2023-11-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='nome_aluno',
        ),
        migrations.CreateModel(
            name='Aluno_Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.aluno')),
                ('nome_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
        ),
    ]
